### ISSUE TITLE
How much traffic would this handle?

### ISSUE THREAD

**Issue by port19x** [DhanrajHira/seadex_api#2]
This seems like a good step towards the ominous torrent mode I've been spreading rumors about for the past few weeks.
It's hard to estimate the userbase, but I'd estimate ~1K-10K requests / day of traffic.
In case I'm not familiar, I'm from [ani-cli](https://github.com/pystardust/ani-cli).

**Comment by DhanrajHira** [comment]
@ura43 The hosted instance runs on a VPS with ample resources (at least for this kind of load). While I am not entirely satisfied with the implementation's performance, even in its current state 10k requests per day should be no problem at all.

**Comment by port19x** [comment]
Good to know. Even at an absolute peak, weeks after implementing and polishing, I don't see the load exceeding 100K / day.
Exciting project, I hope you continue to polish it
